version: '3.8'

services:
  db:
    image: postgres:16
    container_name: pass-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PassDB
    ports:
      - "5432:5432"
    volumes:
      - passdb:/var/lib/postgresql/data
    networks:
      - pass-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pass-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    networks:
      - pass-network

volumes:
  passdb:

networks:
  pass-network: